name: wine-env
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - jupyterlab==4.1.2
  - jupyterlab-git==0.50.0
  - nb_conda_kernels==2.3.1
  - r-car==3.1_2
  - r-cowplot==1.1.1
  - r-irkernel==1.3.2
  - r-tidymodels==1.1.0
  - r-tidyverse==2.0.0
  - r==4.1
  - r-base==4.1.3
prefix: C:\Users\xinru\miniconda3.2\envs\wine-env
